import java.util.HashMap;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;

/*
Consider all integer combinations of ab for 2  a  5 and 2  b  5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?
 */

public class main {
    public static  void main(String[] args) {
        HashSet<Set<Entry<Integer, Integer>>> distinctTerms = new HashSet<Set<Entry<Integer, Integer>>>();
        for (int a = 2; a <= 100; a++) {
            for (int b = 2; b <= 100; b++) {
                int size = distinctTerms.size();
                distinctTerms.add(primeFactorizationOfPower(a, b));
                if (distinctTerms.size() == size) {
                    System.out.println(a + " " + b);
                }
            }
        }
        
        System.out.println(distinctTerms.size());
    }

    private static Set<Entry<Integer, Integer>> primeFactorizationOfPower(int a, int b) {
        HashMap<Integer, Integer> factorization = new HashMap<Integer, Integer>();
        for (int i = 2; i <= a;) {
            if (a%i == 0) {
                a /= i;
                if (factorization.containsKey(i)) {
                    factorization.put(i, factorization.get(i) + b);
                } else {
                    factorization.put(i, b);
                }
                i = 2;
            } else {
                i++;
            }
        }
        return factorization.entrySet();
    }
}